### ISSUE TITLE
Missing Data Issue

### ISSUE THREAD

**Issue by statasaurus** [VIS-SIG/Wonderful-Wednesdays#14]
Hello! 
Thank you for running this. I was interested in working on the current wonderful wednesday, but when I went to that folder there was only a read me. Is the data available somewhere else? 
Cheers,
Christina

**Comment by Lorenz-U** [comment]
Hello Christina,
Thank you for reaching out! This time, we do not provide any data but ask the participants to submit their favorite COVID-19 visualization. This can be based on any data. Furthermore, it can be produced by someone else (for example, you found it in a journal) or done by yourself. You can add your comments and suggest improvements. So, we go with a bit of a different "style" this time. Next time, we will provide a data set again and will go back to our "usual set-up".
Hope this helps.
Best regards,
Lorenz
